### ISSUE TITLE
Move project to create-react-app

### ISSUE THREAD

**Issue by arojunior** [arojunior/awesome-feed#44]
The project started with CRA, but I ejected it and I now I think that it was a mistake.

Does anybody want to help me out to put it back into CRA?

**Comment by kaskelotti** [comment]
You can't put it back, at least with the provided tools. It is stated in the docs
> npm run eject

**Note: this is a one-way operation. Once you eject, you can’t go back!**

Based on the documentation, eject will create/update you package.json file to conrtain all the depencies, instead of working behind the scenes.

You **might** be able to bring it back through source control, but based on what I understood from the commit history, the eject was done quite some time ago.

**Comment by arojunior** [comment]
Yes, you're right. There's no tools to put it back automatically,  that's why I'm looking for help, because we need to do it manually.

**Comment by calebissharp** [comment]
I can attempt to put it back!

**Comment by arojunior** [comment]
closed by #45
